dist:
  module: github.com/open-telemetry/opentelemetry-collector # the module name for the new distribution, following Go mod conventions. Optional, but recommended.
  name: otelcol-custom # the binary name. Optional.
  description: "Custom OpenTelemetry Collector distribution" # a long name for the application. Optional.
  otelcol_version: "0.96.0" # the OpenTelemetry Collector version to use as base for the distribution. Optional.
  output_path: ./build/ # the path to write the output (sources and binary). Optional.
  version: "1.0.0" # the version for your custom OpenTelemetry Collector. Optional.
#  go: "/usr/bin/go" # which Go binary to use to compile the generated sources. Optional.
#  debug_compilation: false # enabling this causes the builder to keep the debug symbols in the resulting binary. Optional.
extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage v0.96.0
exporters:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter v0.96.0" # the Go module for the component. Required.
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter" # the import path for the component. Optional.
    name: "elasticsearchexporter" # package name to use in the generated sources. Optional.
    path: "./exporter/elasticsearchexporter" # in case a local version should be used for the module, the path relative to the current dir, or a full path can be specified. Optional.
receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.96.0
replaces:
  - github.com/elastic/go-docappender => github.com/carsonip/go-docappender 533abc382d1b9d53a583f368f4963419163ee56d
  - go.opentelemetry.io/collector/exporter => go.opentelemetry.io/collector/exporter fbc0ce074899244ebd05090f98adf072e50b2412
#  # a list of "replaces" directives that will be part of the resulting go.mod
#  - github.com/open-telemetry/opentelemetry-collector-contrib/internal/common => github.com/open-telemetry/opentelemetry-collector-contrib/internal/common v0.40.0
